#if !defined(_CLASSIC_WATCH_H)
#define _CLASSIC_WATCH_H

#if !defined(PACKAGE)
#define PACKAGE "org.example.look"
#endif

#ifdef  LOG_TAG
#undef  LOG_TAG
#endif
#define LOG_TAG "look"

/* Angle */
#define HOUR_ANGLE 30
#define MIN_ANGLE 6
#define SEC_ANGLE 6
#define MONTH_ANGLE 30
#define WEEKDAY_ANGLE 51
#define BATTERY_START_ANGLE 195
#define BATTERY_ANGLE 0.6f

/* Layout */
#define BASE_WIDTH 360
#define BASE_HEIGHT 360

#define BATTERY_START_POS_X 147
#define BATTERY_START_POS_Y 105
#define BATTERY_OFFSET_X -25
#define BATTERY_OFFSET_Y 15

#define MODULE_MOONPHASE_SIZE 240
#define MODULE_DAY_NUM_SIZE 100
#define MODULE_DAY_NUM_RIGHT_PADDING 15
#define MODULE_MONTH_SIZE 128
#define MODULE_WEEKDAY_SIZE MODULE_MONTH_SIZE

#define BG_PLATE_WIDTH 120
#define BG_PLATE_HEIGHT 120

#define HANDS_SEC_WIDTH 30
#define HANDS_SEC_HEIGHT 360
#define HANDS_MIN_WIDTH 30
#define HANDS_MIN_HEIGHT 360
#define HANDS_HOUR_WIDTH 30
#define HANDS_HOUR_HEIGHT 360
#define HANDS_BAT_WIDTH 10
#define HANDS_BAT_HEIGHT 117
#define HANDS_MODULE_CALENDAR_WIDTH 20
#define HANDS_MODULE_CALENDAR_HEIGHT 128

#define HANDS_BAT_Y_PADDING 44
#define HANDS_BAT_SHADOW_PADDING 3
#define HANDS_SEC_SHADOW_PADDING 5
#define HANDS_MIN_SHADOW_PADDING 9
#define HANDS_HOUR_SHADOW_PADDING 9

#endif
